
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ tpl .Values.resource.pullSecret.name . }}
  namespace: {{ tpl .Values.resource.pullSecret.namespace . }}
stringData:
  dockerhub-secret.yaml: |
    service:
      registry:
        dockerhubToken: {{ .Values.Installation.V1.Secret.Registry.Dockerhub.Token | quote }}
